var GAME_LEVELS = [
  ["                                                                                ",
   "  x                                                                        x    ",
   "  x                                              yyyy                      x    ",
   "  x                                              oooo                      x    ",
   "  x                                                                        x    ",
   "  x                                                                        x    ",
   "  x                                                             yyyyy      x    ",
   "  x                          yyyyy                              ooooo      x    ",
   "  x                          ooooo       zxx!!!!!!!!                       x    ",
   "  x                                      xxx!!!!!!!!!                      x    ",
   "  x                                     xxxx!!!!!!!!!!                     x    ",
   "  x                                    xxxxx!!!!!!!!!!!                    x    ",
   "  x                      o           oxxxxxx!!!!!!!!!!!!   o               x    ",
   "  x                o    xxx          xxxxxxx!!!!!!!!!!!!! xxx           xoox    ",
   "  x          o    xxx   xxx!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx    ",
   "  x         xxx   xxx!!!xxx!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    ",
   "  x @       xxx!!!xxx!!!xxx!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    ",
   "  xxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "      x!!!x                                                                     ",
   "      xxxxx                                                                     ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],

   ["x                                                                                                                 ",
     "x                                           yyyyyyy         yyyy                                                  ",
     "x                                             ooo            oo                                                   ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                    oo                                                           ",
     "x                                                    yy         x o x                                             ",
     "x             yyyyyyyyyyy                 o                     x o x                                             ",
     "x              o o o o o                 xxx                   bx o x                                             ",
     "x    x                                                         xx o x                                             ",
     "x    xz                                                         x o x                                             ",
     "x    xx                                        oo               x o x                                             ",
     "x    x                                        xxxx          xx  x o x                                             ",
     "x    x   o                                                  x   x o x                                             ",
     "x    x  xx                                                  x  ox o x                                             ",
     "x    x   x                x      x                          x  xx o x                                             ",
     "x    x   x                x      x                          x   x o x                                             ",
     "x    xo  x                x      x                          xo  x o x                                             ",
     "x    xx  x                x      x                          xx  x o x                                             ",
     "x    x   x                x      x                          x   x o x                                             ",
     "x    x  ox                x      x                          x  ox o x                                             ",
     "x    x  xx                x      x                          x  xx o x                                             ",
     "x    x   x                x                                 x   x o x                                             ",
     "x    x   x                x      yyyy                       xo  x o x                                             ",
     "x    xo  x                x       oo                        xx  x o x                                             ",
     "x    xx  x                x      x                          x   x o x                                             ",
     "x    x   x                x      x               oo         x  ox o x                                             ",
     "x                         x      x              xxxx        x  xx o x                                             ",
     "x       @                 x  oo  x       oo     xxxx        x   x o x                                             ",
     "x    xxxxx                x  xx  x      xxxx    xxxx            x o x                                             ",
     "x!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!xxxx            x!!!x                                             ",
     "x!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!xxxx!!!!!!!xxxxxxxxxx                                             ",
     "x!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!xxxx!!!!!!!xxxxxxxxxx                                             "],

     ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "x         x   x   x   x         x x   x x                         x         x",
      "x         yyyyy   yyyyy         yyy   yyy                         x         x",
      "x @        o o     o o           o     o                          x         x",
      "xxxxx                         o     o     o                  xxx      z     x",
      "x   x                        xxx!!!xxx!!!xxx            xxx                 x",
      "x   x                       xxxx!!!xxx!!!xxxx                     x         x",
      "x   x                      xxxxx!!!xxx!!!xxxxx                    x         x",
      "x   x o o       o       o xxxxxx!!!xxx!!!xxxxxx o o               x         x",
      "x   xxxxxx!!!!!xxx!!!!!xxxxxxxxxx!xxxxx!xxxxxxxxxxxx!!!!!!!!!!!!!!x         x",
      "x        x!!!!!xxx!!!!!x         v     v           x!!!!!!!!!!!!!!x         x",
      "x        x!!!!!xxx!!!!!x                           x!!!!!!!!!!!!!!x         x",
      "x        x!!!!!xxx!!!!!x                           x!!!!!!!!!!!!!!x         x",
      "x        x!!!!!xxx!!!!!x                           x!!!!!!!!!!!!!!x         x",
      "x        xxx!xxxxxxx!xxx                           x!xxxxxxxxxxxxxx    o    x",
      "x        x  v       v                               v    x x                x",
      "x        x                                               yyy                x",
      "x        x                                                o                 x",
      "x        x                                                                  x",
      "x        x                                                                  x",
      "x        x                                                                  x",
      "x        x                yyy                                               x",
      "x        x                 o                o       o           oo     o    x",
      "x        x                                 xxx!!!!!xxx!!!!!!!!!xxxx!!!xxx!!!x",
      "x        x                               xxxxx!!!!!xxx!!!!!!!!!xxxx!!!xxx!!!x",
      "x        x                             xxxxxxx!!!!!xxx!!!!!!!!!xxxx!!!xxx!!!x",
      "x        x                         z xxxxxxxxx!!!!!xxx!!!!!!!!!xxxx!!!xxx!!!x",
      "x                                  xxxxxxxxxxx!!!!!xxx!!!!!!!!!xxxx!!!xxx!!!x",
      "x           o       o            xxxxxxxxxxxxxxx!xxxxxx!x!x!x!xxxxxx!xxxxx!xx",
      "x       =x!xxx!!!!!xxx!!!!!!!!!!!x              v      v v v v      v     v x",
      "x        x!xxx!!!!!xxx!!!!!!!!!!!x                                          x",
      "x=o    o x!xxx!!!!!xxx!!!!!!!!!!!x                                          x",
      "xxx    xxx!xxx!!!!!xxx!!!!!!!!!!!x                                          x",
      "x        x!xxx!!!!!xxx!!!!!!!!!!!x                                          x",
      "x        x!xxx!!!!!xxx!!!!!!!!!!!x                                          x",
      "x  x  x  x!xxx!!!!!xxx!!!!!!!!!!!x                                          x",
      "x        x!xxx!!!!!xxx!!!!!!!!!!!x                                          x",
      "x        x!xxx!!!!!xxx!!!!!!!!!!!x                                          x",
      "x   xx   x!xxx!!!!!xxx!!!!!!!!!!!x                            xxx     x     x",
      "x        x!xxx!!!!!xxx!!!!!!!!!!!x                    xxx             x o o x",
      "x        yyyyyyyyyyyyyyyyyyyyyyyyy              o                   x x o o x",
      "x b                                            xxx                    x o o=x",
      "xxxxxxxxxx                                                            x o o x",
      "xxxxxxxxxx                                                            x o o x",
      "xxxxxxxxxx|  |   | | | | |  |  |                                      x o o x",
      "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],


  ["                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "      x     x  xxxx    x     x         x         x         x   xxx   xx     x   ",
   "       x   x  x    x   x     x          x       x x       x    xxx   x x    x   ",
   "        x x   x    x   x     x           x     x   x     x     xxx   x  x   x   ",
   "         x    x    x   x     x            x   x     x   x      xxx   x   x  x   ",
   "         x    x    x    x   x              x x       x x       xxx   x    x x   ",
   "         x     xxxx      xxx                x         x        xxx   x     xx   ",
   "                                                                                ",
   " @                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
